### ISSUE TITLE
archive is broken in 2020

### ISSUE THREAD

**Issue by dansinker** [sinker/impeachment.fyi#15]
as per @miklb's warning when he first implemented the much better archives, it's now broken in 2020. Any chance we can get a fix on this?

**Comment by miklb** [comment]
Yes, I was thinking about it last night and can send a PR tonight

Cheers.

Michael

**Comment by miklb** [comment]
Hey, sorry on the delay. New team I’m on went down a person. Catching up this morning & will have time over weekend. Cheers.

**Comment by miklb** [comment]
I just pushed up a branch with a fix for 2020. I’m going to start rethinking my logic now. 

Currently untested, shifting machines to limit yak shaving.
