### ISSUE TITLE
Weekly Archives

### ISSUE THREAD

**Issue by miklb** [sinker/impeachment.fyi#4]
@sinker can you outline where & how you want these displayed? As in headlines/summaries/etc

**Comment by dansinker** [comment]
Haha, thanks for looking into it. Basically I'd love for the archive page
to have weekly header dividers, so the last 5 days would fall under "week
2" the 5 before that "week 1" etc.

**Comment by miklb** [comment]
Okey doke can do.

**Comment by miklb** [comment]
Little trickier to do than i initially thought with it being a single data file and the date the top key. 

That said, I'm making progress and intend to find a solution.

**Comment by dansinker** [comment]
Omg please don't lose time over this.

**Comment by miklb** [comment]
Oh, I'm not. It just turned into an interesting question that has given me something to think about while doing some more mundane tasks.

**Comment by miklb** [comment]
I need to clean up the markup and test for more than 2 weeks but I have it working.

This was a [fun dive back into Liquid](https://raw.githubusercontent.com/miklb/impeachment.fyi/archive_weekly/archive.md)!



![Impeachment fyi - archives_week](https://user-images.githubusercontent.com/819716/66264898-f755e880-e7da-11e9-9416-11bd0639605f.png)

**Comment by dansinker** [comment]
Whoa!

**Comment by miklb** [comment]
had a few minutes to clean this up and push to the PR preview here https://deploy-preview-6--eloquent-noyce-debe7b.netlify.com/archive

If you want to add, I'll move the PR from draft status.

cheers

**Comment by miklb** [comment]
Closed in #6
